rpm-software-management/dnf-plugins-core

package/dnf-plugins-core.spec
Reported-by: Radek Holy <rholy@redhat.com>
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> spec: exclude __pycache__ dir

dnf-plugins-core.spec
The major version bump did not introduce backwards incompatible changes.
It's needed to fix our CI job!
I did just some sanity tests since I don't expect that something should break.
=> spec: allow DNF 1.x.x

dnf-plugins-core.spec
Currently, it removes dnf-plugins-core when fresh installations of F22 are upgraded.
```
...
Installing:
python-dnf-plugins-core  noarch 0.1.7-1.fc22             updates-testing  77 k
replacing  dnf-plugins-core.noarch 0.1.5-1.fc22
...
python3-dnf-plugins-core noarch 0.1.7-1.fc22             updates-testing  53 k
replacing  dnf-plugins-core.noarch 0.1.5-1.fc22
...
```
It would be nice if it could get into F22+ as soon as possible so that as few users as possible end up with no dnf-plugins-core package installed.
=> spec: fix an upgrade path from dnf-plugins-core <= 0.1.5

plugins/builddep.py, plugins/debuginfo-install.py, plugins/dnfpluginscore/lib.py
This PR depends on #116 and should be merged after it.
=> Fix for Bug 1265622 - 'dnf builddep' is not always as 'clever' as yum-builddep or dnf download --source

plugins/repoquery.py
Fix 'dnf repoquery --info' when character like u'\u2019' appears.
=> repoquery: Fix UnicodeEncodeError with --info (RhBug:1264125)

dnf-plugins-core.spec
The spec indicates there should be a constraint on the python(3)-hawkey Requirement, but unfortunately, the hawkey version variable isn't properly declared. This PR corrects that by properly referencing the global variable set in the spec.
=> Fix hawkey version constraint

AUTHORS, plugins/builddep.py
The build-dependency information for a source package is contained in
the repodata.  Because of this, it is not necessary to download the 
source package to evaluate the build dependencies.
=> builddep: do not download source package

plugins/copr.py
Please see <https://bugzilla.redhat.com/show_bug.cgi?id=1304615>
=> copr: fix traceback when trying to enable non-existing project (RhBug: 304615)

dnf-plugins-core.spec
Unfortunately %python_provide is still providing py2 package by default
even on f24, f25 (rawhide). So let's require explicitly.
Reference: https://github.com/rpm-software-management/dnf/pull/493
Reported-by: Jaroslav Mracek <jmracek@redhat.com>
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> spec: correctly set up requirements for python subpkg

plugins/copr.py
This pull request fixes how `copr.conf` was read so that it doesn't trigger a traceback anymore (reported by Korora's @csmart).
In addition, I've added support for selecting Mageia chroots automatically.
(Obsoletes #169)
=> Fix reading the copr.conf file and add Mageia chroot selection support

dnf-plugins-core.spec
When we have installed python-dnf-plugins-core (before %python_provide) it is
possible to install python3-dnf-plugins-core with new version because it conflicts
with python2-dnf-plugins-core which is not installed. Let's fix it.
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> spec: explicitly conflict with python-%{name} with different version

plugins/copr.py
COPR provides support for building packages for Fedora, CentOS/RHEL, and Mageia. Tweaking the wording to be more generally applicable ensures clarity in this regard.
=> copr: Tweak wording to be more generic

dnf-plugins-core.spec, plugins/download.py
Because we can't define CLI option --destdir twice (once in download plugin, once in dnf), I moved the copying functionality to dnf and made download plugin use it.
This pull request and the [pull request for dnf](https://github.com/rpm-software-management/dnf/pull/810) have to be accepted at the same time, because one doesn't work without the other (breaks download plugin).
Because --destdir will be run under root, all downloaded (to another location) packages now have permissions set to 777 since most expected usecases involve a non-privileged user doing something with the files (probably moving).
=> Download plugin: Move --destdir to dnf (RhBug:1279001)

doc/copr.rst, plugins/copr.py
Adds ``dnf copr list`` subcommand to show enabled Copr repositories. Changes the original ``dnf copr list name`` subcommand (which lists available Copr repositories for a given ``name``) to ``dnf copr list-user name``.
=> copr: added list command to show enabled Copr repositories

plugins/repoclosure.py
The changes should fix problem that added filters were not applied.
Additionally it apply filters before applying new filters to increase
performance.
=> Fix repoclosure with best and newest option

plugins/repoclosure.py
This is a follow-up of rpm-software-management/dnf-plugins-extras/pull/50
With `--check`, we want to check repo closure for all packages in the specified repositories.
With `--best`, we want to only use the latest versions of each package across all repos.
When using both options, we need to enumerate the packages to be checked from the `--check` repos before reducing the package set to the latest versions for `--best`, as that might eliminate some of the packages from the `--check` repos. The existing code already inhibits using `available.latest()` early on for `--best` when using `--check`, and this commit does the deferred application of `available.latest()` for the case when `--check` and `--best` are used together.
I would like to write a test case for this but can't get my head …
=> Fix repoclosure --check interaction with --best

doc/download.rst
This will unify documentation of options with dnf core where downloaddir option
is described. Both options remain as aliases, but it should provide better user
experiences.
=> Rename --destdir to --downloaddir in doc

AUTHORS
I think you forgot me when copying the leaves plugin from dnf-plugin-extras
=> AUTHORS: add leaves author

doc/download.rst, doc/repoclosure.rst
It adds description of arch option for download command.
It also adds hint about --forcearch option for repoclosure because in some cases
users can be confused by --arch option.
https://bugzilla.redhat.com/show_bug.cgi?id=1489724
=> Add hint for --arch options (RhBug:1489724)

doc/versionlock.rst
Adding a note about the resolution of https://bugzilla.redhat.com/show_bug.cgi?id=1431491. (I'd tripped over this myself before.)
=> Note versionlock works on packages absent from repos (RhBug:1431491)

plugins/copr.py
This PR adds support for detecting openSUSE Leap and Tumbleweed and setting the correct default based on that.
This is required for [RH#1570418](https://bugzilla.redhat.com/show_bug.cgi?id=1570418).
=> copr: Add openSUSE support

plugins/copr.py
It's supposed to be `%_target_cpu`, not `%target_cpu`...
=> copr: Fix macro expansion for openSUSE

dnf-plugins-core.spec, plugins/copr.py
`platform.linux_distribution()` is slated for removal in Python 3.7.
The "distro" Python module provides a suitable replacement.
=> copr: Use python-distro for distro identification

dnf-plugins-core.spec
Due to conflict of dnf-2.8.9+ with yum, it is nice to provide yum-utils due to
increase compatibility and not breaking work-flows.
=> Add provide of yum-utils

plugins/download.py
With --resolve and --source options download also uninstalled
dependencies.
https://bugzilla.redhat.com/show_bug.cgi?id=1571251
=> Do not ignore --resolve in dnf download --source (RhBug:1571251)

tests/support.py, tests/test_config_manager.py, tests/test_download.py, tests/test_repoclosure.py, tests/test_repograph.py, tests/test_reposync.py
RepoStub inherits methods from dnf.repo.Repo instead of faking them.
It is required due to changes in DNF.
=> Fix RepoStub in unit tests

doc/versionlock.rst
I've made two minor clarifications to doc/versionlock.rst. In one case (the sentence about "an exclude for the package name itself"), I'm assuming I've got the meaning correct. If not, I submitted these as two commits so the second is easier to back out.
=> Minor clarifications for doc/versionlock.rst

dnf-plugins-core.spec
Unfortunately the plugin is not well documented even in yum and still doesn't
have the final behavior, therefore it will be better to not introduce it into rhel.
=> Exclude leaves plugins from rhel builds

plugins/leaves.py
This reverts commit 786b1c5e7180eb6b9d5af8245be69f69d59cad0e.
This optimization seems to be broken in latest rawhide.
=> Revert "Reduce query creation for leave plugin about 18x"

plugins/config_manager.py
https://bugzilla.redhat.com/show_bug.cgi?id=1615416
This won't fix the bug completely - there is also problem with the * in the baseurl. This issue resolves PR https://github.com/rpm-software-management/libdnf/pull/581
=> Add characters into repo URL sanitization (RhBug:1615416)

doc/repoclosure.rst, plugins/repoclosure.py
When the repoclosure command gets non-existing package in the --pkg option,
it shows an error message and returns error code.
https://bugzilla.redhat.com/show_bug.cgi?id=1571622
=> repoclosure on non-existing package ends with error (RhBug:1571622)

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py, doc/dnf-utils.rst, doc/package-cleanup.rst, doc/reposync.rst, libexec/dnf-utils.in
* Adds missing dnf-utils (yum-utils), yumdownloader and package-cleanup man pages
* Adds man page symlinks for the remaining commands
* Removes incompatible options from package-cleanup
=> Compat fixes for dnf-utils

plugins/download.py, tests/test_download.py
Downloading multiple packages with same NEVRA into same location results
in fail during checksum check. Now only one package with same NEVRA will
be downloaded.
https://bugzilla.redhat.com/show_bug.cgi?id=1612874
=> Download only packages with unique NEVRAs (RhBug:1612874)

plugins/copr.py
This fixes the second issue in [Bug1628888](https://bugzilla.redhat.com/show_bug.cgi?id=1628888) when copr didn't recognize a Rawhide repo and tried to use Fedora 30 instead.
=> copr: fix enabling Rawhide repository (RhBug:1628888)

dnf-plugins-core.spec
I missed the fact that, for Fedora <= 29, dnf-utils was not built any
more with the original commit.  My mistake.  Let's revert it now as a
quick fix and consider a better fix later.
This reverts commit 9d07c0da599448e963e214ef50160b8b1f164b96.
=> Revert "spec: bcond: dnfutils -> yumcompatibility"

plugins/copr.py
This gets rid of the traceback and fixes disabling repos with the old format.
=> copr: fix disabling repos with old filenames and repo IDs (RhBug:1644563)

plugins/download.py, tests/support.py, tests/test_download.py
$ dnf download acpi-1.7-9.fc28.x86_64.rpm
Last metadata expiration check: 0:20:41 ago on Thu 25 Oct 2018 01:27:34 AM EDT.
Traceback (most recent call last):
File "/usr/bin/dnf", line 98, in <module>
main.user_main(MAPPING[command] + args, exit_code=True)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
errcode = main(args)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
return _main(base, args, cli_class, option_parser_class)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
return cli_run(cli, base)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 115, in cli_run
cli.run()
File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 1055, in run
return self.command.run()
File …
=> [download] Fix traceback when local rpm / url is passed

plugins/download.py, tests/test_download.py
"dnf download dnf" will not download src rpm with this patch.
It makes behavior similar with yumdowloader.
https://bugzilla.redhat.com/show_bug.cgi?id=1666648
=> Not download src without --source (RhBug:1666648)

plugins/versionlock.py
Signed-off-by: Adam Miller <admiller@redhat.com>
Previously if you attempted to load this plugin via the python api it would fail because `self.cli` is never instantiated.
```
In [2]: # %load /home/admiller/prep_dnf_transaction.py
...: #!/usr/bin/python3
...: import dnf
...: base = dnf.Base()
...: base.conf.read()
...: base.read_all_repos()
...: base.init_plugins()
...: base.pre_configure_plugins()
...: base.configure_plugins()
...: base.fill_sack()
...: base.read_comps()
...:
...:
...:
Failed loading plugin: copr
Failed to synchronize cache for repo 'rcm-tools-fedora-rpms', disabling.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2eb170f829f3> in <module>()
8 …
```
=> don't assume cli for sack operation in versionlock to honor api load

dnf-plugins-core.spec, plugins/local.py, tests/test_config_manager.py
Plugins get parser from DNF.
Don't rely on iniparse module and don't import it.
=> Remove dependency on iniparse

plugins/leaves.py
This prevents a situation where package A depends on
Adep, two installed packages B and C provides Adep,
but neither B or C are shown by dnf leaves even though
either B or C (but not both) can be uninstalled
without problems.
The drawback is that the user may look at dnf leaves
and try to 'dnf uninstall B C' and be confused why dnf
also wants to uninstall A.
However, we already have a similar situation when
dnf leaves shows all packages in a strongly connected
component. Eg. git depends on perl-Git and perl-Git depends
on git, so both are shown by dnf leaves when nothing else
depends on git or perl-Git and the user might similarly be
confused why dnf wants to uninstall git when trying to
uninstall perl-Git.
=> leaves: ignore multiply satisfied dependencies

plugins/download.py
Fix "No such file or directory" error on the taget file while
downloading an rpm, caused by os.path.samefile() failing to stat() it.
=> download: fix downloading an rpm from a URL

doc/config_manager.rst
It explicitly states that config-manager accept a repoid. Using the
repoid is the best way because it is unique identificator of
the repository.
https://bugzilla.redhat.com/show_bug.cgi?id=1686779
=> [doc] improve documentation of config-manager (RhBug:1686779)

dnf-plugins-core.spec, doc/reposync.rst, plugins/reposync.py
Added new --remote-time command line switch. With this switch on
the reposync command will try to set the timestamps of the downloaded
files to those on the remote side.
https://bugzilla.redhat.com/show_bug.cgi?id=1688537
Requires https://github.com/rpm-software-management/libdnf/pull/725
=> [reposync] Enable timestamp preserving for downloaded data (RhBug:1688537)

plugins/reposync.py
Reposync should retrieve identical copy of the repo. Do not filter
packages according to enabled module streams.
https://bugzilla.redhat.com/show_bug.cgi?id=1714788
=> [reposync] Download packages from all streams (RhBug:1714788)

dnf-plugins-core.spec
We can switch this on after yum package is retired.
https://bugzilla.redhat.com/show_bug.cgi?id=1707552
=> [spec] Postpone yumcompatibility to F31 (RhBug:1707552)

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py
Since this man page is redirected to dnf.plugin.changelog man page
and there is no relevant config file for this plugin remove it.
=> Remove yum-changelog.conf(5) man page (RhBug:1673920)

doc/needs_restarting.rst, plugins/needs_restarting.py
This is the original implementation from the needs-restarting script in
yum-utils, with a few tweaks (e.g. no versions are printed to keep
things simple).
Original RHEL-7 request:
https://bugzilla.redhat.com/show_bug.cgi?id=1192946
New RHEL-8 request:
https://bugzilla.redhat.com/show_bug.cgi?id=1639468
=> needs-restarting: add --reboothint option

plugins/local.py
It reflects the new default in dnf skip_if_unavailable option. Without
the change, the plugin local will caused to stop working of DNF due to
missing repodata for local plugin repository. The issue is critical for
newly installed machines.
=> Set skip_if_unavailable=True for plugin local repository

AUTHORS, plugins/local.py
Currently, _dnf_local repo is only preferred by name, but it'll not always work; e.g. when a repository name starts with capital letters. 
Instead of relying on alphabetical preference, which (I think) is not even guaranteed, we set its cost to 500 so that it is preferred to normal repositories which has the cost of 1000.
=> Set the cost of _dnf_local repo to 500, to make it preferred to normal repos

dnf-plugins-core.spec, plugins/builddep.py
https://bugzilla.redhat.com/show_bug.cgi?id=1663619
=> [builddep] Report all rpm errors (RhBug:1663619,1658292)

doc/config_manager.rst, plugins/config_manager.py
The PR changes behaviour of `--setopt` in config-manager plugin.
`--setopt:` Fix crash with `--save --dump` 
Adds globs support to `--setopt repoid` (`--setopt=*-debuginfo.key=value`).
` --setopt=key=value` is not applied to repositories config
`--setopt` and empty list of repositories (RhBug:1702678)
`--setopt`: Add check for existence of input repositories
Solves: https://bugzilla.redhat.com/show_bug.cgi?id=1702678
It is more compatible with YUM now.
=> Behaviour of "--setopt" in config-manager plugin (RhBug:1702678)

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py
This ensures that the man page actually says "yum-utils" instead of
"dnf-utils" in the beginning.
=> [spec] Generate yum-utils(1) instead of symlinking (RhBug:1676418)

dnf-plugins-core.spec
Such a rename would be a risky move that could break something in the
infrastructure so let's leave the dnf-utils name on Fedora.
=> [spec] Don't rename dnf-utils -> yum-utils on F31

dnf-plugins-core.spec, plugins/debuginfo-install.py
Basically rewrites the plugin to:
* Install the reuqested version if specified on the command line
* Install the version of the installed base package if it's installed
* Install the latest available debuginfo version of packages otherwise
* Properly install both debuginfo and debugsource packages where
available
* Print informative messages for packages that do not have debuginfo
* More effectively query and install the packages in one step
https://bugzilla.redhat.com/show_bug.cgi?id=1586059
https://bugzilla.redhat.com/show_bug.cgi?id=1586084
---
Requires this: https://github.com/rpm-software-management/dnf/pull/1425
The tests are here: https://github.com/rpm-software-management/ci-dnf-stack/pull/566
=> Refactor and fix the behavior of debuginfo-install

plugins/copr.py
With config like
$ cat /etc/dnf/plugins/copr.d/test.conf
[local]
hostname = localhost
protocol = http
port = 55555
The 'dnf copr disable ...' failed before because `self.copr_hostname`
looks like 'something:55555'.
=> copr: fix disable if copr instance has non-default port

plugins/copr.py
There's concept of "directories" (copr dirs) in copr, so each project
can have multiple directories (not only the main one).  For example in
some project (say @copr/copr-dev) there's always the main directory;
that is identified by the copr name itself (e.g. '@copr/copr-dev').  But
there might be other directories which are identified by additional
SUFFIX (e.g. '@copr/copr-dev:SUFFIX', typically '@copr/copr-dev:pr:22')
So there might be additional colon(s) in repoID we didn't expect before,
so the 'dnf copr list' was malformed.  See the difference in 'dnf copr
list' output, before/after this fix:
- copr.fedorainfracloud.org:group_copr:copr-dev/pr/788 (disabled)
+ copr.fedorainfracloud.org/group_copr/copr-dev:pr:788 (disabled)
The previous format of the string was invalid, and user wasn't …
=> copr: fixup listing copr repos with separate directory

dnf-plugins-core.spec
Otherwise "rpm --verify python3-dnf-plugins-core" is complaining:
$ rpm --verify python3-dnf-plugins-core
.M.......  g /var/cache/dnf/packages.db
https://bugzilla.redhat.com/show_bug.cgi?id=1754463
=> [spec] Specify attributes for ghost file (RhBug: 1754463)

dnf-plugins-core.spec, plugins/download.py
Adds the --debugsource option next to the --debuginfo one to support
downloading the *-debugsource packages.
Also changes the behavior to support more than one of [--source,
--debuginfo, --debugsource] options at the same time and downloads all
of the requested packages.
https://bugzilla.redhat.com/show_bug.cgi?id=1637008
tests PR: https://github.com/rpm-software-management/ci-dnf-stack/pull/592
=> download: add the --debugsource option

plugins/builddep.py
Solver must decide whether richdeps that has no matches is required or
it can be skipped.
https://bugzilla.redhat.com/show_bug.cgi?id=1756902
=> Fix incorrect handling richdeps in buildep (RhBug:1756902)

doc/versionlock.rst, plugins/versionlock.py
Versionlock add/exclude commands are now able to insert into
versionlock.list file patterns without converting it into NEVRAs. It is
usable for example for locking package to versions not available yet:
$ dnf version lock --raw add 'bash-5.*'
Adding versionlock on: bash-5.*
This command will keep the bash package on major version 5 and dnf will
still consume any future updates as far as they do not bump the major
version.
Without --raw switch used, the versionlock would take only currently
available packages into account:
$ dnf versionlock add 'bash-5.*'
Adding versionlock on: bash-0:5.0.7-1.fc30.*
https://bugzilla.redhat.com/show_bug.cgi?id=1645564
=> [versionlock] Add --raw option (RhBug:1645564)

dnf-plugins-core.spec
The version bump from the PR
https://github.com/rpm-software-management/dnf/pull/1530 was not
applied.
=> Bump required dnf version

dnf-plugins-core.spec
It turns out this conflict is no longer needed thanks to commit acd13c91
which postponed yumcompatibility (and thus the compat man pages) to
Fedora 31. (Moreover, the conflict should have been under the
dnf-plugins-core package where the man page is shipped, as opposed to
dnf-utils).
Note that the conflict itself doesn't hurt anything but we should keep
things easy to understand.
=> [spec] Revert conflict on yum-plugins-copr

doc/builddep.rst, plugins/builddep.py
Using --skip-broken makes builddep command tollerant to uninstallable
packages. All other (installable) build dependencies are going to be
installed.
https://bugzilla.redhat.com/show_bug.cgi?id=1628634
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/689
=> [builddep] Accept --skip-broken switch (RhBug:1628634)

plugins/versionlock.py
When you move locked version of the package in versionlock.list config
file to newer version, you should be able to upgrade the package to this version.
https://bugzilla.redhat.com/show_bug.cgi?id=1726712
The test: https://github.com/rpm-software-management/ci-dnf-stack/pull/678
=> [versionlock] Don't apply excludes on @System (RhBug:1726712)

plugins/reposync.py
This is a regression, reposync always used to apply excludes and
includes. It only needs to ignore modular dependencies to be able to
synchronize non-enabled streams.
https://bugzilla.redhat.com/show_bug.cgi?id=1750273
=> [reposync] Apply only modular excludes (RhBug:1750273)

plugins/config_manager.py
DNF has the `--config` argument. It defines path to the configuration
file. The config_manager plugin used the configuration from the path
but the changes were allways saved into /etc/dnf/dnf.conf.
The PR fixes it. The changes are saved to the original
configuration file.
=> Fix: config_manager respect config file location during save

plugins/reposync.py
reposync --latest will download all lates non-modular packages plus all
packages for contexts with latest version for each module stream.
https://bugzilla.redhat.com/show_bug.cgi?id=1775434
=> Redesign reposync --latest for modular system (RhBug:1775434)

doc/CMakeLists.txt, doc/conf.py
The migrate plugin is Python-2-only, and so should be its documentation.
Note: this will not remove references in other files (really just index.rst). Doing so would be non-trivial and is probably not worth the effort. A broken link should be red flag enough for users not to try to use a plugin. Certainly better than shipping documentation for something that won't be available anyway IMHO.
=> [doc] Skip creating and installing migrate documentation for Python 3+

plugins/config_manager.py
The arguments are checked directly inside configure.
Parser error called explicitly
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1782822
=> config-manager calls parser error when without options (RhBug:1782822)

dnf-plugins-core.spec
Since rpm-4.15.0, text following %else or %endif directives produces
a warning.
Also, escaping the %{?rhel} macro, so that it's not expanded.
=> [spec] Add comments after %endif to separate line

dnf-plugins-core.spec, plugins/config_manager.py
The arguments `--set-enabled`, `--set-disabled` are valid for `config-manager` plugin. 
The fix moves they from general DNF arguments into the plugin arguments.
Note:
There are another "config-manager" arguments `--enable` and `--disable` in the DNF general section. They cannot be moved into config-manager plugin because of Python argparser abbreviation.
Added warning when `--enablerepo`/`--disablerepo` arguments were passed. These global DNF arguments have no meaning with confim-manager plugin. Users are confused and use them instead of --set-enabled/--set-disabled. But it does not work.
Depends on: https://github.com/rpm-software-management/dnf/pull/1621
=> Move args --set-enabled/--set-disabled, add messages (RhBug:1727882)

doc/repomanage.rst, plugins/repomanage.py, tests/support.py
In order to support modular content we have to load repodata with
repodata/modules.yaml present.
If repodata are not present in the target path there is no way to tell
which packages belong to which stream and repomanage will continue to
show packages from different streams as obsoleting each other.
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/825
https://bugzilla.redhat.com/show_bug.cgi?id=1804720
=> Add modular support to repomanage (RhBug:1804720)

doc/debug.rst, plugins/debug.py
- use standard demands.resolving to actually run the transaction
- install-only packages are not removed by default (only when new option --remove-installonly is used)
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/862
The bug: https://bugzilla.redhat.com/show_bug.cgi?id=1844533
=> debug-restore enhancement

setup.cfg
tox.ini is not read by the pep8speaks bot, setup.cfg is. Unifying the
line length limit with what is used in dnf now.
=> Move tox.ini -> setup.cfg and increase line length to 120

plugins/reposync.py
This covers situation when package with the newest NEVRA is part of
an older version of a stream.
https://bugzilla.redhat.com/show_bug.cgi?id=1833074
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/875
=> [reposync] Add latest NEVRAs per stream to download (RhBug: 1833074)

plugins/copr.py
These are not necessarily other copr repositories, but rather any
(external) repositories.  We can not disable them "separately" by
'dnf copr disable', etc.  Printing them in 'dnf copr list' isn't
semantically correct.
Fixes: rhbz#1871373
=> copr: don't try to list runtime dependencies

doc/post-transaction-actions.rst, plugins/post-transaction-actions.py
Currently, the plugin is using a `set` to store commands to be executed.  Unfortunately, `set` is unordered and the execution order cannot be predicted, which makes it difficult to work with actions.
The plugin reads action files and saves them in ordered lists, so changing the `set` to a `list` makes the whole experience much better.  For example, if we have an action file with:
```
/usr/bin/screen:in:echo step 1
/usr/bin/screen:in:echo step 2
/usr/bin/screen:in:echo step 3
```
with the original logic you will see all possible orders of these steps when you install, upgrade, or reinstall the `screen` package.
with the proposed change you will always get steps in the order they are defined.
=> post-transaction-actions: make execution order predictable

plugins/repomanage.py
Always expire the repo, otherwise repomanage could use cached metadata
and give identical results for multiple runs (depending on metadata_expire
config value) even if the actual repo changed in the meantime.
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/913
=> [repomanage] Don't use cached metadata

doc/reposync.rst, plugins/reposync.py
YUMv3 reposync used to have --gpgcheck option to remove packages that fail GPG signature checking after downloading.
This patch implements the option for DNF.
https://bugzilla.redhat.com/show_bug.cgi?id=1856818
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/900
=> [reposync] Check GPG signatures of downloaded packages (RhBug:1856818) 

plugins/versionlock.py
There is an initiative for removal of politically problematic words from
IT projects (blacklist, whitelist, slave).
=> Set blacklist subcommand as deprecated

doc/reposync.rst, plugins/reposync.py
Previous description may have implied that user must use the --source
option to download also the source packages and that they will be
excluded otherwise.
The new description is more in line with other options (e.g. --arch or
--newest-only) and implies that the option only limits the reuslt.
= changelog =
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1914827
=> [reposync] Improve documentation of --source option

dnf-plugins-core.spec, doc/release_notes.rst, plugins/config_manager.py
https://github.com/rpm-software-management/dnf/pull/1743 removes code this package uses, so we replaced it. We need to ensure that dnf does not permit version of this package before 4.0.20 to be installed else they will not be able to resolve the class. See https://github.com/rpm-software-management/dnf/pull/1743#pullrequestreview-615177905 for context.
=> Removed dependency on dnf.yum.misc.Checksum class

plugins/copr.py
The output from linux_distribution() changed so it returns:
>>> distro.linux_distribution()
('Fedora Linux', '35', '')
=> Fix 'dnf copr enable' on Fedora 35

plugins/copr.py
= changelog =
msg: dnf copr enable on CentOS Stream should enable centos stream chroot, not epel 8
type: bugfix
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1994154
=> Fix baseurl for centos stream chroot

plugins/groups_manager.py
= changelog =
msg: groups-manager uses for matching packages full NEVRA and not only name.
type: enhancement
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2013633
=> groups-manager: More benevolent resolving of packages (RhBug:2013633)

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py, doc/index.rst, doc/modulesync.rst, plugins/CMakeLists.txt, plugins/modulesync.py
It will download module metadata from all enabled repositories,
module artifacts and profiles of matching modules. Then it creates
a repository.
Requires: https://github.com/rpm-software-management/dnf/pull/1794
For RHEL8 it requires: https://github.com/rpm-software-management/libdnf/pull/1381
=> Add new command modulesync

plugins/repoclosure.py, tests/test_repoclosure.py
For reviewing repoclosure results, it is handy to have raw counts sometimes.  Incremental fixes are easier to identify when you can see the numbers going down.
=> Add counts of missing deps

plugins/copr.py
This way it doesn't try to connect to `https://http//url` if `--hub` started with `http://`.
=> copr: allow specifying protocol as part of --hub

dnf-plugins-core.spec, plugins/debug.py
The debug plugin used `base.sack._rpmdb_version()` method. Which is actually the private method hawkey.Sack._rpmdb_version()` from libdnf.
The patch uses the `base._ts.dbCookie()` method. This method was added to DNF 4.11.0. And internally it calls the new official API function `rpm.TransactionSet.dbCookie()` from librpm. This is a necessary step to allow the `._rpmdb_version()` method to be removed from libdnf.
Requires: https://github.com/rpm-software-management/dnf/pull/1811
=> plugin debug: Use base._ts.dbCookie() to determining rpmdb version

doc/repomanage.rst, plugins/repomanage.py
= changelog =
msg:           repomanage: Add new option --oldonly
type:          enhancement
resolves:      https://bugzilla.redhat.com/show_bug.cgi?id=2034736
resolves:      https://bugzilla.redhat.com/show_bug.cgi?id=2058676
=> feat(repomanage): Add new option --oldonly

plugins/post-transaction-actions.py
It prevent traceback in output when reason change is in transaction
CI test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1093
=> Skip all non rpm tsi for transaction_action plugins (rhbug:2023652)

plugins/repomanage.py
= changelog =
msg: [repomanage/reposync] Modules are used only when they belong to target repo
type: bugfix
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2072441
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1094
=> repomanage: Use modules only from repo they are handling

plugins/copr.py
Packages built in epel-9 chroots are almost always compatible with CentOS Stream 9.  Not having the copr plugin guess this chroot is causing user friction.  Users are creating epel-9 chroots expecting them to work for both CentOS Stream 9 and RHEL 9.  When they get reports about `dnf copr enable` not working, they try to add a centos-stream-9 chroot, only to discover the dependencies they need from EPEL are not available.
Instead of making the majority of CentOS Stream users include an explicit chroot argument, let's reserve that workaround only for the people that don't want their CentOS Stream systems picking the EPEL chroot.
=> copr: Guess EPEL chroots for CentOS Stream (RhBug:2058471)

doc/builddep.rst, plugins/builddep.py
Defining RPM macros in `builddep` command is not supported for source rpms. Therefore adding note into man page and warning when using the `-D` or `--define` argument with source rpm.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2077820.
=> builddep: Warning when using macros with source rpms

CMakeLists.txt, dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py, doc/index.rst, doc/system-upgrade.rst, etc/CMakeLists.txt, etc/systemd/CMakeLists.txt, etc/systemd/dnf-system-upgrade-cleanup.service, etc/systemd/dnf-system-upgrade.service, plugins/CMakeLists.txt, plugins/system_upgrade.py, tests/test_system_upgrade.py
Move `system-upgrade` plugin from `dnf-plugins-extras` to `dnf-plugins-core` to enable offline upgrades on RHEL systems.
Related PRs from other components:
`dnf-plugins-extras`: https://github.com/rpm-software-management/dnf-plugins-extras/pull/210
`dnf`: https://github.com/rpm-software-management/dnf/pull/1846
`ci-dnf-stack`: https://github.com/rpm-software-management/ci-dnf-stack/pull/1150
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2054235.
=> Move system-upgrade plugin to core (RhBug:2054235)

AUTHORS, plugins/system_upgrade.py
Adding security filter support makes it easier and safer, for example, to upgrade select packages from `updates-testing` and other testing repositories. I stumbled into this while testing updates from Bodhi, and also found a bug report about it from last year [(RhBug:1939975)](https://bugzilla.redhat.com/show_bug.cgi?id=1939975).
It's a two-line change, enabling it only for `offline-upgrade`. I tested it by refreshing the metadata using the four available filter options (`--advisory`, `--bugfix`, `--security`, and `--enhancement`) and it did filter them correctly. I downloaded a single package using `--advisory` and it installed correctly on boot. Other non-upgraded packages where left unchanged, and the package is working correctly.
I was not sure if I should update the documentation or …
=> offline-upgrade: add support for security filters (RhBug:1939975)

plugins/needs_restarting.py
This PR contains the implementation of the idea from Fedora bugzilla [Comment #12](https://bugzilla.redhat.com/show_bug.cgi?id=2137935#c12). See discussion also https://github.com/rpm-software-management/dnf-plugins-core/pull/466#issuecomment-1306983291
=> needs_restarting: Fix boot time derivation for systems without RTC

AUTHORS, doc/system-upgrade.rst, plugins/system_upgrade.py, tests/test_system_upgrade.py
Adds an option to shutdown the system after updates have been installed, instead of rebooting.
[Based on this comment](https://unix.stackexchange.com/a/704106/533888).
=> [system-upgrade] Add --poweroff option to reboot subcommand

doc/copr.rst, plugins/copr.py
= changelog =
msg: [copr] Also read chroot configs from other files in copr.conf.d
type: enhancement
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2091662
This PR is an alternative solution to #458, which allows other config files to override the main Copr config for chroot configs in the `[main]` section.
It adds a new optional config file called `copr.vendor.conf` that allows vendors to specify what distro their downstream is compatible with on COPR. This solves issues regarding COPR on Ultramarine Linux, Nobara, and risiOS.
=> copr: Acknowledge downstream compatibility for non-EPEL distros

dnf-plugins-core.spec, doc/system-upgrade.rst, plugins/system_upgrade.py
The `distro` package is not available in the minimal installation of related downstreams where the warning should be displayed. Therefore dropping the implementation from the upstream and affected distributions will handle the situation by themselves.
related link: https://bugzilla.redhat.com/show_bug.cgi?id=2152846
=> system-upgrade: Drop warning in upstream

dnf-plugins-core.spec, plugins/system_upgrade.py
As the `distro` package is not available in the BaseOS, the warning implementation will be shown always, but only in related downstreams.
= changelog =
type: bugfix
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2152846
=> system-upgrade: Show warning always for a downstream

dnf-plugins-core.spec, plugins/system_upgrade.py
Backport #474 to `9.2.0` branch.
=> system-upgrade: Show warning always for a downstream (backport to 9.2.0)

.github/workflows/ci.yml
Since we have a separate branch for dnf4 in `ci-dnf-stack` use it to run integration tests.
=> Run dnf-plugins-core (dnf4) CI againts dnf-4-stack branch

plugins/config_manager.py
Also change the name of the "crepo" argument from "repo" to "section" and fix its description to unite it with the description in documentation.
Resolves: https://github.com/rpm-software-management/dnf/issues/1883
=> [config-manager] Allow to specify the "main" section

plugins/download.py
Currently, `dnf download --resolve` will always download weak dependencies, disregarding the `install_weak_deps` option value: _(tested in AlmaLinux 9.0 container)_
```
$ dnf download --setopt=install_weak_deps=0 --url --alldeps --resolve kernel | wc -l
121
$ dnf download --setopt=install_weak_deps=1 --url --alldeps --resolve kernel | wc -l
121
```
With this trivial patch it works as user may expect it to work - not downloading linux-firmware and few other packages:
```
$ dnf download --setopt=install_weak_deps=0 --url --alldeps --resolve kernel | wc -l
116
$ dnf download --setopt=install_weak_deps=1 --url --alldeps --resolve kernel | wc -l
121
```
=> download plugin: respect install_weak_deps option value

plugins/post-transaction-actions.py
Prevent " AttributeError: module 'libdnf.conf' has no attribute 'ConfigParser_substitute'"
=> ConfigParser.substitute

doc/reposync.rst, plugins/reposync.py
By default reposync is not allowed to write files outside of repository download path (by default ./<repo id>). But there are some repositories that store packages using relative parent paths (e.g. ../packages-store/f/foo.rpm).
This patch introduces new --safe-write-path option that can override this limitation and set a root directory that is considered safe for writing.
For example `dnf reposync --repoid=the_repo --safe-write-path=.` will allow reposync to write files not only to `./the_repo` directory but also to current working directory itself.
= changelog =
msg: With --safe-write-path option reposync can download repositories with relative package locations (like ../package-store/f/foo.rpm)
type: enhancement
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1898089
=> reposync: Implement --safe-write-path option (RhBug:1898089)

plugins/builddep.py
dsFromHeader() and dsOfHeader() header methods were removed in rpm 4.19, passing header to rpm.ds constructor is the preferred way since rpm 4.8 / RHEL 6.
=> Avoid a long obsolete rpm API use

plugins/needs_restarting.py
Limit handling of the issue to only this specific use case, otherwise throw the exception as any other DBUS-related call.
Follow-up to the fix from https://github.com/rpm-software-management/dnf-plugins-core/pull/487.
=> needs-restarting: Small refinement of NoUnitForPID handling

plugins/copr.py
It would always load the regular copr.conf no matter what due to it not being wrapped inside an else statement. Thus, making the feature unusable.
=> Fixed copr.vendor.conf not loading

plugins/copr.py
On Asahi Fedora Linux Remix, this can occur when doing a dnf copr enable:
Repository 'epel-37-x86_64' does not exist in project '@asahi/mesa'
There are two bugs here, the code doesn't recongize this as a Fedora distro and defaults to x86_64 when in this case it's actually an aarch64 system.
=> "dnf copr enable" on "Asahi Fedora Linux Remix" guesses epel..x86_64

etc/systemd/dnf-system-upgrade.service
Add a systemd dependency to wait until upgrade service is finished before executing the poweroff when passing the `--poweroff` option in `system-upgrade` plugin.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2211844
=> system-upgrade: Wait until the upgrade is done before poweroff (RhBug:2211844)

plugins/needs_restarting.py, tests/test_needs_restarting.py
For now this PR is only for purposes of showing the problem and *one* potential fix to it.
Related bug:
https://bugzilla.redhat.com/show_bug.cgi?id=2212953
I can fixup the commit later for formatting, etc. -- in the meantime I am going to try to gather more data from cPanel customers experiencing this to see just what the heck is in the smaps files for the failing cases.
Regardless, this appeared to me to be a real bug in the upstream code, so I figured I'd approach it in that manner.
=> Prospective fix for strange issue with invalid UTF-8 with test

plugins/needs_restarting.py
A host might reasonably have only kernel-core installed without kernel-modules or the kernel metapackage installed.
=> [needs-restarting] add kernel-core to reboot list

plugins/needs_restarting.py
To fully update CPU microcode, a reboot is needed because the microcode update should be applied before starting a kernel and other process.
Therefore recommend a reboot after installing or updating microcode_ctl package.
https://issues.redhat.com/browse/RHEL-4600
=> needs-restarting: Add microcode_ctl to a reboot list

plugins/download.py, plugins/needs_restarting.py, plugins/repoclosure.py
Prepare for switching to not loading filelists metadata by default. Explicitly request the metadata by plugins that need them.
Requires: https://github.com/rpm-software-management/dnf/pull/2012.
Targetted for: https://issues.redhat.com/browse/RHEL-12355.
=> Request filelists metadata for plugins needing that

doc/needs_restarting.rst
Also, add a warning in the docs if the system is running in RTC
docs for this change: https://github.com/rpm-software-management/dnf-plugins-core/pull/527
=> Document needs-restarting boot time

dnf-plugins-core.spec
Use globs to cover both dnf4 man files and dnf symlinks.
This should also fix the [failing ELN builds](https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf-nightly/build/7322846/) where the following error occurred:
```
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/share/man/man8/dnf-leaves.8.gz
/usr/share/man/man8/dnf-show-leaves.8.gz
Finish: rpmbuild dnf-plugins-core-4.7.0-0.20240418004803.4.6.0+3.g22b390e.eln136.src.rpm
```
Related: https://github.com/rpm-software-management/dnf5/pull/1424.
=> spec: Simplify man page files

doc/needs_restarting.rst, plugins/needs_restarting.py
Upstream commit: 74de8fe84679e509b16ca1d3f12b7d292210ca27
Upstream commit: a0ac8717219a1ec9f466162e87f40afa9aa65284
Upstream commit: 486e9d4d7f03309f3eaf71e297ae956e18357bd8
Resolves: https://issues.redhat.com/browse/RHEL-14900
@inknos, could you please review this rhel-9.5 backport of your commits?
=> rhel-9.5: Fixes for RHEL-14900

etc/systemd/dnf-system-upgrade.service
Upstream commit: 4615b3213659351d9933ac91e595bd236618f649
Resolves Rhbug:2219233
Resolves: https://issues.redhat.com/browse/RHEL-13053
@evan-goode, could you please review this rhel-9.5 backport of your trivial commit?
=> rhel-9.5 fix for RHEL-13053

doc/needs_restarting.rst, plugins/needs_restarting.py
This revers rhel-9.5 commits:
486e9d4d7f03309f3eaf71e297ae956e18357bd8
a0ac8717219a1ec9f466162e87f40afa9aa65284
74de8fe84679e509b16ca1d3f12b7d292210ca27
Resolves: https://issues.redhat.com/browse/RHEL-39775
because it causes a regression.
@evan-goode, could you review this revert?
=> rhel-9.5: revert systemd boot time

doc/needs_restarting.rst, plugins/needs_restarting.py
Since commit a0ac8717219a1ec9f466162e87f40afa9aa65284 "dnf needs-restarting -s" failed to spot services started withing few seconds before updating their RPM package.
The cause was using systemd start time instead of a kernel boot time when computing an absolute start time of processes.
This patch removes using the systemd start time until a proper fix is found.
https://issues.redhat.com/browse/RHEL-39775
=> needs-restarting: Revert using systemd start time

AUTHORS, plugins/download.py
Fixes #535 . Tested with debuginfo package `libstdc++` on Fedora 40.
There're compatible interface changes to `_get_packages_with_deps` that removes the unused parameter `source` and now accepts `set[Package]` objects as input.
We hope to get a new release after this is merged and eventually available in Fedora 40. So, our effort to remove the current internal workaround is minimized.
CC @kontura
=> fix(download): resolve dependencies for debuginfo and debugsource packages

plugins/needs_restarting.py
When setting the reboot hint, search for newly installed or updated packages that provide the package names listed in `NEED_REBOOT`. This allows the `needs-restarting` plugin to detect if any alternative kernels have been installed/updated since the system last booted.
=> needs-restarting: detect packages providing NEED_REBOOT.

CMakeLists.txt, README.rst, dnf-plugins-core.spec, doc/CMakeLists.txt, plugins/CMakeLists.txt
This adds -DWITHOUT_DEBUG:str=1 CMake option to disable installing debug plugin (i.e. debug-dump and debug-restore).
The plugin is unhelp and broken.
https://issues.redhat.com/browse/RHEL-23706
=> build: Disable debug plugin on Fedora > 40 and RHEL > 9

dnf-plugins-core.spec
Some relative symlinks had an incorrect nesting:
$ rpm -qlv dnf-plugins-core-4.7.0-2.el10.noarch | grep dnf-offline
lrwxrwxrwx    1 root     root                       70 Jun  6 02:00 /usr/share/man/man8/dnf-offline-distrosync.8.gz -> ../../../../../../../../../usr/share/man/man8/dnf4-system-upgrade.8.gz
lrwxrwxrwx    1 root     root                       70 Jun  6 02:00 /usr/share/man/man8/dnf-offline-upgrade.8.gz -> ../../../../../../../../../usr/share/man/man8/dnf4-system-upgrade.8.gz
Also rpmlint and recenct rpmbuild complained on using absolute symlinks:
dnf-plugins-core.noarch: W: symlink-should-be-relative /usr/share/man/man8/dnf4-offline-distrosync.8.gz /usr/share/man/man8/dnf4-system-upgrade.8.gz
dnf-plugins-core.noarch: W: symlink-should-be-relative …
=> spec: Fix symbolic links to packaged files

dnf-plugins-core.spec
This effectively reverts commit
8a7a02b1e9573d86f5e6a430c61bf514e4856d31 because RHEL enebles these plugins since RHEL 9.3.
Resolves: https://issues.redhat.com/browse/RHEL-44922
=> Enable leaves and show-leaves plugins for RHEL

doc/copr.rst
It was pointed that "dnf -4 copr enable ..." performs IPv6 connections. The cause is that _download_repo() function used urllib.request.urlopen() instead of dnf.base.urlopen() on purpose: It needs to process an HTTP status code and a custom HTTP header.
Unfortunatelly urllib.request.urlopen() does not support specifying an address family preference.
A long term fix would be replacing urllib.request.urlopen() with a pycurl Python library (or less likely augment dnf/libdnf/librepo to expose an HTTP layer).
As a short gap solution, this patch documents this deficiency and points the user to a global address family setting.
https://bugzilla.redhat.com/show_bug.cgi?id=2303712
=> doc: copr plugin does not respect IP family preference

plugins/expired-pgp-keys.py
Because gpg signatures of packages are checked before actually running the `plugins.pre_transaction` hook, we need to call it earlier.
=> expired-pgp-keys: Fix calling the hook at resolved time

plugins/copr.py
This fixes a bug on Amazon Linux 2023 that prevents COPR from enabling packages, even if they have been built using amazonlinux chroot:
https://github.com/amazonlinux/amazon-linux-2023/issues/643
Repro on an ec2 instance trying to enable [sklarsa/zfs-al2023](https://copr.fedorainfracloud.org/coprs/sklarsa/zfs-al2023):
```sudo dnf copr enable -y sklarsa/zfs-al2023
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.
The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.
Please do not file bug reports about …
```
=> Add Amazon Linux to copr chroots

doc/needs_restarting.rst, plugins/needs_restarting.py
For consumers of `dnf4 needs-restarting`'s output, it's useful to separate the systemd services needing restart vs. the processes not managed by systemd that need restarting. This new `dnf4 needs-restarting --exclude-services` ONLY prints information about processes NOT managed by systemd, and for listing systemd services that need to be restarted, the existing `--services` flag can be used.
When both `--services` and `--exclude-services` are passed `--exclude-services` is ignored.
For https://issues.redhat.com/browse/RHEL-56137.
CI PR on the way.
=> needs-restarting: Add --exclude-services

CMakeLists.txt, doc/bootc.rst, doc/needs_restarting.rst, plugins/bootc.py, plugins/copr.py, plugins/needs_restarting.py
Implement the 'install' subcommand for the bootc plugin and add documentation.  Most of the options for this subcommand will come from global dnf command line option settings.  The only option not handled is --os=OSNAME from rpm-ostree.
https://issues.redhat.com/browse/SWM-3090
=> bootc: Implement the 'install' subcommand

plugins/bootc.py
See commit messages.
Also merges changes from master branch.
For https://issues.redhat.com/browse/SWM-3432
=> bootc: Simplify I/O with rpm-ostree subprocess

plugins/reposync.py
This is a backport for the commit https://github.com/rpm-software-management/dnf-plugins-core/commit/05706d097b30632b823bb619d9ba634297c82863 into the rhel-9.6 branch.
Resolves: https://issues.redhat.com/browse/RHEL-40914
=> rhel-9.6: Fix for RHEL-40914 (reposync: Respect --norepopath with --metadata-path)

plugins/needs_restarting.py
Resolves https://issues.redhat.com/browse/RHEL-35577.
Get the boot time from `UnitsLoadStartTimestamp` if systemd is available, but make sure to use the kernel boot time for calculating process start times using data from procfs. The previous attempt [1] at this failed to do so and introduced a regression [2].
Also, get the kernel boot time from the btime field of /proc/stat instead of calculating it from /proc/uptime, to be consistent with what procps-ng does.
[1] https://github.com/rpm-software-management/dnf-plugins-core/pull/527
[2] https://issues.redhat.com/browse/RHEL-39775
=> needs-restarting: Get boot time from systemd UnitsLoadStartTimestamp

plugins/needs_restarting.py, tests/test_needs_restarting.py
needs-restarting currently checks the major:minor device of each mmapped file and ignores files from devices with major version 0, considering them "not regular files". According to the kernel docs [1], a major version of 0 is for "unnamed devices, e.g. non-device mounts".
But ignoring files on 00:xx devices seems to not be a valid strategy. From my testing, in containers and in virtual machines especially, "regular files" managed by DNF are often on these devices. For example:
```
docker run -it --rm fedora:40 stat /usr/bin/sleep
File: /usr/bin/sleep
Size: 36864     	Blocks: 72         IO Block: 4096   regular file
Device: 0,100	Inode: 2403790     Links: 1
...
```
This patch removes this filter so that we just check that a file has a corresponding file path. There are files that have …
=> needs-restarting: "Regular files" are often on 00:xx devices

plugins/bootc.py
We're planning to support transient package installations only for now, so the rpm-ostree based `dnf4 bootc install` command is no longer planned.
=> Call bootc instead of rpm-ostree, remove `dnf4 bootc install`

plugins/needs_restarting.py
Backport of https://github.com/rpm-software-management/dnf-plugins-core/pull/560 to rhel-9.6.
Upstream commit: 17b38c8041564119c4fb99215da6b3257d1d5d66
Resolves https://issues.redhat.com/browse/RHEL-14900.
=> rhel-9.6: Fix for RHEL-14900 ("needs-restarting -r" reports no reboot required if RTC is not in UTC)

dnf-plugins-core.spec
Fedora 41 has completed the migration to DNF5, so ELN (the future RHEL 11) is now ready to follow suit.
Related: https://github.com/rpm-software-management/dnf/pull/2161
/cc @evan-goode
=> spec: toggle dnf5_obsoletes_dnf for RHEL 11

plugins/reposync.py
Download each package only once if it would have been saved to the same location. This can occur if the repository metadata contains duplicate entries for the same package.
Resolves: https://issues.redhat.com/browse/RHEL-64320
=> reposync: Avoid multiple downloads of duplicate packages

doc/needs_restarting.rst, plugins/needs_restarting.py
Upstream commit: https://github.com/rpm-software-management/dnf-plugins-core/pull/556/commits/39d2681244899fb5918c17e04c417b13721b8c23
Upstream commit: https://github.com/rpm-software-management/dnf-plugins-core/pull/556/commits/69776828a9a15418761184778c1e08b7f0237dd5
Resolves: https://issues.redhat.com/browse/RHEL-56137.
=> rhel-10.0 backport: needs-restarting: Add --exclude-services

plugins/copr.py
This is a backport of the upstream commit: https://github.com/rpm-software-management/dnf-plugins-core/commit/4c2b209d2367e48f8aeef18e9c696c42774cc6eb for rhel-9.6 branch.
=> rhel-9.6: Fix for RHEL-56143

doc/needs_restarting.rst
This updates the needs-restarting documentation following https://github.com/rpm-software-management/dnf-plugins-core/pull/560.
Follow-up to https://github.com/rpm-software-management/dnf-plugins-core/pull/528 which was later partially reverted.
=> doc: needs-restarting uses UnitsLoadStartTimestamp boot time

README.rst
Companion to https://github.com/rpm-software-management/dnf/pull/2221. @ppisar
=> README: direct to Libera.Chat instead of Freenode

README.rst
dnf-plugins-core counterpart to https://github.com/rpm-software-management/dnf/pull/2232.
Move the message about IRC to the top of the README so it's more visible.
Remove dead link to the bug reporting guide.
=> README: link to #dnf instead of #yum IRC

plugins/manifest.py
Since RPM 6.0.0-beta manifest plugin fails like this:
File "/usr/lib/python3.14/site-packages/dnf-plugins/manifest.py", line 116, in run
self._new()
~~~~~~~~~^^
File "/usr/lib/python3.14/site-packages/dnf-plugins/manifest.py", line 147, in _new
self._add_packages_to_manifest(self._resolve_packages(), arch, manifest, modules_info)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.14/site-packages/dnf-plugins/manifest.py", line 250, in _add_packages_to_manifest
pkg.checksum.method, pkg.checksum.digest = self._retrieve_pkg_checksum(dnf_pkg)
~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
File "/usr/lib/python3.14/site-packages/dnf-plugins/manifest.py", line 451, in _retrieve_pkg_checksum
method = …
=> manifest: Adapt to RPM 6.0.0 beta

plugins/copr.py
If the plugin was executed on Fedora Rawhide, Copr releasever was silently overriden to "rawhide" regardless of what was explicitly set in copr.conf. As a result, it was impossible to configure the plugin to use something else than fedora-rawhide chroot on those systems.
That manifested in ci-dnf-stack where "Test the COPR plugin" test (dnf/plugins-core/copr.feature:2) passed everywhere except of Rawhide.
This patch relaxes the override to be only applied when there is no explicit configuration in the plugin configuration. I.e. the override is now effective only when the Copr chroot is autodetected.
The override was orginally added because of
<https://bugzilla.redhat.com/show_bug.cgi?id=1628888>.
Resolve: #592
=> copr: Respect releasever set in copr.conf
