dnf-plugins-core.spec
See https://github.com/rpm-software-management/hawkey/pull/91
=> spec: add a %{snapshot} macro for easier snapshot building

plugins/copr.py
Hello,
this PR fixes [1244125](https://bugzilla.redhat.com/show_bug.cgi?id=1244125).
Can you please review it @evilkost ?
=> [copr] allow utf-8 user input (RhBug:1244125)

plugins/download.py
4th " breaks code highlight in my editor and is obviously wrong
=> Remove extra quotation mark in comment

plugins/debuginfo-install.py
try <name>-debuginfo first then <srcname>-debuginfo (RhBug:1159614)
=> Fix for Bug 1159614 - dnf debuginfo-install kernel-PAE picks wrong debuginfo package

dnf-plugins-core.spec, doc/debuginfo-install.rst, etc/dnf/CMakeLists.txt, etc/dnf/plugins/CMakeLists.txt, etc/dnf/plugins/debuginfo-install.conf, plugins/debuginfo-install.py, plugins/dnfpluginscore/lib.py
enable debuginfo repositories if there are debuginfo packages installed and autoupdate=on
=> update debuginfo packages (RhBug: 1024701)

dnf-plugins-core.spec
* Subpackage with python2 files now prefixed with python2- instead of python-
* Added %python_provide macro for each subpackage to correctly provide python/python2
versions
* Fix BuildRequires/Requires to require python2 packages in f23+ instead of just python
* Removed Group tags because it's not used anywhere
* Remove hacks around copying sources for building python3 version:
There is no point to do this, because CMake provides ability to easy do builds
out-of-tree, so let's just have 2 build directories for py2/py3.
* Use %license macro for license
* Use %make_build and %make_install macros
* Use %python2_sitelib for python2 package instead of %python_sitelib
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> spec: improve python packaging according to new guidelines

tests/support.py
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1331981
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> tests/support: set priority and cost in RepoStub

dnf-plugins-core.spec
It produce a problem with upgrade from fc25 to fc26.
https://bugzilla.redhat.com/show_bug.cgi?id=1470843
=> Solve conflict with migrate plugin (RhBug:1470843)

plugins/download.py, plugins/repoclosure.py
https://bugzilla.redhat.com/show_bug.cgi?id=1476834
=> Fix the problems with --arch option (RhBug:1476834)

dnf-plugins-core.spec, plugins/local.py
It allows to disable local repository from command line.
Requires: https://github.com/rpm-software-management/dnf/pull/897
=> Use new hook pre_config for local plugin

plugins/versionlock.py
lock/exclude of packages not available in repositories any more was
not applying.
https://bugzilla.redhat.com/show_bug.cgi?id=1431491
=> version lock works on unavailable packages (RhBug:1431491)

doc/versionlock.rst
I added a bit more detail about the exclude directive, to make things more explicit. And I cleaned up some minor grammar and formatting issues.
=> Add a bit more detail, plus grammar and style fixes

plugins/debuginfo-install.py
https://bugzilla.redhat.com/show_bug.cgi?id=1516857
=> Report no match for debug-install command (RhBug:1516857)

doc/debuginfo-install.rst
https://bugzilla.redhat.com/show_bug.cgi?id=1576594
=> Enhance documentation for debuginfo-install (RhBug:1576594)

dnf-plugins-core.spec, plugins/download.py, plugins/repomanage.py, tests/support.py, tests/test_download.py
Additionally it allows to download packages from url
Requires: https://github.com/rpm-software-management/dnf/pull/1110
=> Make progressbar of download packages sensitive to -q option

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/conf.py
- yum-plugin-* provides for copr and versionlock plugin
- manpages for yum-copr, debuginfo-install, needs-restarting, repo-graph,
repoclosure, repomanage, reposync, yum-builddep, yum-config-manager,
yum-debug-dump, yum-debug-restore, yum-versionlock
=> YUM3 compatibility layer

plugins/reposync.py
Requires: https://github.com/rpm-software-management/dnf/pull/1179
=> allow reposync to work with --destdir (RhBug:1582152)

dnf-plugins-core.spec, plugins/repomanage.py, tests/support.py
It is only on command request. It should solve the issue for parsing
outputs.
https://bugzilla.redhat.com/show_bug.cgi?id=1626011
=> Redirect repo progress to std error (RhBug:1626011)

plugins/debuginfo-install.py
https://bugzilla.redhat.com/show_bug.cgi?id=1585137
=> Report not found debuginfo packages (RhBug:1585137)

plugins/generate_completion_cache.py, plugins/local.py
It should prevent problems in performance or stability.
=> Run transaction hook only if transaction

dnf-plugins-core.spec, doc/CMakeLists.txt, doc/changelog.rst, doc/conf.py, doc/index.rst, plugins/CMakeLists.txt, plugins/changelog.py
For viewing the packages changelogs.
=> New dnf changelog plugin

plugins/download.py
https://bugzilla.redhat.com/show_bug.cgi?id=1649627
=> Fix problem with downloading src pkgs (RhBug:1649627)

doc/reposync.rst, doc/versionlock.rst
https://bugzilla.redhat.com/show_bug.cgi?id=1659328
=> Enhance reposync man page

dnf-plugins-core.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1673902
=> Move yum-copr manpage to dnf-plugins-core package (RhBug:1673902)

plugins/copr.py
The current copr frontend code simply ignores additional path
specifiers, so the overall output isn't affected.
We'd like though, if it will be enabled in the corresponding
copr project, diverge slightly the repo files for some
architectures.  Namely to support multilib:
https://pagure.io/copr/copr/issue/1
=> copr: specify arch when requesting repo

plugins/copr.py
=> py3.8: properly escape backslash

plugins/reposync.py
When reposync was used with --delete option and multiple repositories
to sync, only packages from the latest repository were kept and all
downloaded content from former repositories was imediately deleted.
Additionaly it fixes the problem with multiple packages having the same
filename (in different subdirectories) in one repository. In this case
when --delete option was used, only one of those files was kept and the
others were deleted.
https://bugzilla.redhat.com/show_bug.cgi?id=1774103
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/713
=> [reposync] Fix --delete with multiple repos (RhBug:1774103)

plugins/copr.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1777345
=> copr: diferentiate fedora architecture

plugins/copr.py
broken by PR #379
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1777345
=> fixes architecture differentiation for Mageia and OpenSuse

dnf-plugins-core.spec, plugins/download.py, tests/test_download.py
Requires: rpm-software-management/libdnf#902
Tests: rpm-software-management/ci-dnf-stack#800
=> [download] Respect repo priority (RhBug:1800342)

dnf-plugins-core.spec
= changelog =
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1863433
=> spec: Fix building with new cmake macros

plugins/needs_restarting.py
=changelog=
msg: [needs-restarting] fix -r in nspawn containers
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1913962
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1914251
=> [needs-restarting] fix -r in nspawn containers

doc/download.rst
--alldeps option of download command was not documented.
=> Add missing command line option to documentation

dnf-plugins-core.spec, tests/CMakeLists.txt, tests/README
= changelog =
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1916782
=> Replace python-nose with unittest

plugins/versionlock.py
see https://bugzilla.redhat.com/show_bug.cgi?id=1961217
=> Versionlock works correctly with packages with minorbump part of release

plugins/leaves.py
Before:
```
root@rawhide~# dnf leaves
arm-none-eabi-gcc-cs-1:9.2.0-4.fc32.x86_64
automake-1.16.2-1.fc33.noarch
bc-1.07.1-10.fc32.x86_64
bison-3.5-2.fc32.x86_64
cryptsetup-libs-2.3.3-1.fc33.x86_64
dbus-1:1.12.18-1.fc33.x86_64
dbus-broker-23-2.fc33.x86_64
dbus-common-1:1.12.18-1.fc33.noarch
device-mapper-1.02.171-2.fc33.x86_64
device-mapper-libs-1.02.171-2.fc33.x86_64
dnf-4.2.23-1.fc33.noarch
dtc-1.6.0-2.fc33.x86_64
flex-2.6.4-4.fc32.x86_64
gcc-aarch64-linux-gnu-9.2.1-3.fc32.1.x86_64
gcc-arm-linux-gnu-9.2.1-3.fc32.1.x86_64
gcc-c++-10.1.1-1.fc33.x86_64
gcc-riscv64-linux-gnu-9.2.1-3.fc32.1.x86_64
git-2.27.0-1.fc33.x86_64
hostname-3.23-2.fc32.x86_64
htop-2.2.0-8.fc32.x86_64
kmod-27-2.fc33.x86_64
libusb-devel-1:0.1.7-1.fc33.x86_64
linux-firmware-20200519-108.fc33.noarch
lzop-1.04-3.fc32.x86_64 …
```
=> leaves: show strongly connected components

plugins/copr.py
= changelog =
msg: playground command doesn't work
type: bugfix
related: https://bugzilla.redhat.com/show_bug.cgi?id=1955907
=> Disable dnf playground command

doc/versionlock.rst, plugins/versionlock.py
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2013324
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2013332
test https://github.com/rpm-software-management/ci-dnf-stack/pull/1045
=> [versionlock] fix multi pkg lock (RhBug:2001039)

dnf-plugins-core.spec
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> use SPDX format for license

dnf-plugins-core.spec
=changelog=
msg: Update License to SPDX Format
type: enhancement
https://pagure.io/copr/license-validate/raw/main/f/packages-without-spdx-final.txt
=> Update License to SPDX Format

plugins/system_upgrade.py
Correcting changes made to some strings in #467 for localization.
=> [offline-upgrade] Fix strings for l10n

plugins/needs_restarting.py, tests/test_needs_restarting.py
= changelog =
msg: Catch exception in needs-restarting.py when no systemd unit exists for pid
type: bugfix
resolves: 2122587
related: None
=> Add fix and test assertion for "no systemd unit exists for pid"

etc/systemd/dnf-system-upgrade.service
=> system-upgrade: change http to https in unit file

dnf-plugins-core.spec
Related:
- https://github.com/rpm-software-management/dnf5/pull/1425
- https://github.com/rpm-software-management/dnf/pull/2082
=> Prepare for switch of dnf5 in Rawhide

plugins/reposync.py
Resolves: https://issues.redhat.com/browse/RHEL-40914
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1530
=> reposync: Respect --norepopath with --metadata-path

.copr/Makefile
This will give us a repo with the latest snapshot of this project built as an RPM.
=> copr: Set up automatic Copr builds for testing and dev purposes

AUTHORS, plugins/copr.py, plugins/debuginfo-install.py, tests/test_config_manager.py
fixes https://github.com/rpm-software-management/dnf-plugins-core/issues/520
=> Fix missing dnf.cli imports

plugins/multisig.py
If a key in OpenPGP version 6 format format was defined for a repository, the key was always omitted and never imported to pqrpm key store. As a result, packages signed with that key could not be verified:
[...]
Importing GPG key 0xC9D3B13C:
Userid     : "rsa4k_user"
Fingerprint: CE77 8FBE 1E8D 4DD2 7691 FB33 CA58 1189 C9D3 B13C
From       : /root/repo/rsa4k.cert
Key imported successfully
foo                                                             16 MB/s |  16 kB     00:00
Import of key(s) didn't help, wrong key(s)?
Public key for foo-1.0-1.noarch.rpm is not installed. Failing package is: foo-1.0-1.noarch
GPG Keys are configured as: file:///root/repo/rsa4k.cert, file:///root/repo/mldsa87.cert
Error: GPG check FAILED
The cause was that multisig plugin called dnf.crypto.retrieve() to …
=> multisig: Fix importing OpenPGPv6 keys
